### ISSUE TITLE
Missing import for IPython console execution.

### ISSUE THREAD

**Issue by mscheltienne** [autoreject/autoreject#233] opened 2021-10-04 12:37 UTC
While trying out the [new workflow tutorial](https://github.com/autoreject/autoreject/blob/master/examples/plot_autoreject_workflow.py), I ran into a couple of issues with the progress bars. 

In a new environment, in the python console, nothing breaks, and the progress bar work.
With the same environment, in the Spyder IPython console, I get:

```
Running autoreject on ch_type=eeg
Traceback (most recent call last):

  File "/Users/scheltie/Downloads/autoreject.py", line 81, in <module>
    ar.fit(epochs[:20])  # fit on a few epochs to save time

  File "/Users/scheltie/Documents/pyvenv/test/lib/python3.8/site-packages/autoreject-0.3.dev0-py3.8.egg/autoreject/autoreject.py", line 1007, in fit
    _run_local_reject_cv(epochs, thresh_func, this_picks,

  File "/Users/scheltie/Documents/pyvenv/test/lib/python3.8/site-packages/autoreject-0.3.dev0-py3.8.egg/autoreject/autoreject.py", line 766, in _run_local_reject_cv
    local_reject.fit(epochs)

  File "/Users/scheltie/Documents/pyvenv/test/lib/python3.8/site-packages/autoreject-0.3.dev0-py3.8.egg/autoreject/autoreject.py", line 680, in fit
    self.threshes_ = self.thresh_func(

  File "/Users/scheltie/Documents/pyvenv/test/lib/python3.8/site-packages/autoreject-0.3.dev0-py3.8.egg/autoreject/autoreject.py", line 435, in _compute_thresholds
    epochs_interp = _clean_by_interp(epochs, picks=picks,

  File "/Users/scheltie/Documents/pyvenv/test/lib/python3.8/site-packages/autoreject-0.3.dev0-py3.8.egg/autoreject/utils.py", line 228, in _clean_by_interp
    for ch_idx, (pick, ch) in enumerate(_pbar(list(zip(picks, ch_names)),

  File "/Users/scheltie/Documents/pyvenv/test/lib/python3.8/site-packages/autoreject-0.3.dev0-py3.8.egg/autoreject/utils.py", line 179, in _pbar
    pbar = ProgressBar(iterable, mesg=desc, **kwargs)

  File "/Users/scheltie/Documents/pyvenv/test/lib/python3.8/site-packages/mne-0.23.4-py3.8.egg/mne/utils/progressbar.py", line 80, in __init__
    self._tqdm = tqdm(

  File "/Users/scheltie/Documents/pyvenv/test/lib/python3.8/site-packages/tqdm/notebook.py", line 242, in __init__
    self.container = self.status_printer(self.fp, total, self.desc, self.ncols)

  File "/Users/scheltie/Documents/pyvenv/test/lib/python3.8/site-packages/tqdm/notebook.py", line 115, in status_printer
    raise ImportError(

ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
```

Missing `ipywidgets` dependency? If I install it with pip, I then get another error message spam in the console: `ERROR:traitlets:No such comm target registered: jupyter.widget`.

**Comment by hoechenberger** [comment] 2021-10-04 13:14
That's a new dependency for running `openneuro-py` in Jupyter
(running `openneuro-py` from IPython / Jupyter was not possible until … yesterday or so, as `openneuro-py` didn't re-use an existing async event loop, and creating its own in the same thread as IPython / Juypyter would fail)

The obviously simplest solution would be to make `ipywidgets` a hard dependency for `openneuro-py`, but this seems like overkill …

Any suggestions welcome.

FYI I've seen this issue pop up multiple times today during a workshop, so this **is** a problem indeed. Would be grateful for any advice.

cc @agramfort

**Comment by hoechenberger** [comment] 2021-10-04 13:16
@mscheltienne What happens if you use `openneuro-py` version `2021.8`? In Jupyter it is expected to raise an exception, but how does the Spyder IPython console behave?

**Comment by hoechenberger** [comment] 2021-10-04 13:47
@mscheltienne Can you please check if this here works for you?

https://github.com/hoechenberger/openneuro-py/pull/57

If you're running `openneuro-py` from IPython oder Juypyter and ipywidgets cannot be imported, it should now provide a more useful error message. When running outside of Jupyter / IPython, ipywidgets should not be required

**Comment by mscheltienne** [comment] 2021-10-04 14:08
@hoechenberger I guess a similar problem is occurring with `openneuro-py`, but it's not the one at cause here. In this issue, the error is caused by the progress bar displayed by `AutoReject.fit()`, no?

That said, with openneuro version `2021.8`, I do get an error, but maybe not the one you are expecting:

```
Hello! This is openneuro-py 2021.8. Great to see you!

      Please report problems and bugs at
      https://github.com/hoechenberger/openneuro-py/issues

Preparing to download ds002778 ...
Retrieving up to 12 files (5 concurrent downloads).
Traceback (most recent call last):

  File "/var/folders/b1/kx2x00x95ls80zzkct4647sh0000gn/T/ipykernel_10464/1020394274.py", line 14, in <module>
    openneuro.download(dataset=dataset, target_dir=target_dir,

  File "/Users/scheltie/Documents/pyvenv/test/lib/python3.8/site-packages/openneuro/download.py", line 637, in download
    asyncio.run(_download_files(**kwargs))

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 33, in run
    raise RuntimeError(

RuntimeError: asyncio.run() cannot be called from a running event loop
```

The same code snippet works in the terminal, so the error is restricted to the IPython console. I'll check the PR code and reply on the PR.

**Comment by hoechenberger** [comment] 2021-10-04 14:14
Thank you! Yes everything you reported is expected. Can you now try again with the PR branch of openneuro-py I linked above please? :)

**Comment by mscheltienne** [comment] 2021-10-04 14:19
@hoechenberger PR branch or main are both not working. No error was raised, but only the folder structure is created with no actual files..

**Comment by hoechenberger** [comment] 2021-10-04 14:30
@mscheltienne Bummer! I just pushed another change, can you try if that changes anything?

**Comment by mscheltienne** [comment] 2021-10-04 14:52
Hiding my replies, as the original issue is not with `openneuro-py` but with `AutoReject` progress bar(s).

**Comment by hoechenberger** [comment] 2021-10-04 15:03
They **are** related! Because `openneuro-py` uses `tqdm`, which `AutoReject` uses for displaying progress bars too. `openneuro-py` tries to do some clever things to get fancy progress bars in Jupyter, and this then also affects `AutoReject`.

**Comment by mscheltienne** [comment] 2021-10-04 15:11
@hoechenberger Sure they are similar, but it needs to be fixed individually for both no?

Snippet below, not using `openneuro-py` is raising the issue (file pre-downloaded with `openneuro-py`). 

```
import os.path as op

import mne
import autoreject


directory = '/Users/scheltie/Documents/datasets/openneuro/ds002778/'
subject_id = 'pd14'
raw_fname = op.join(directory, f'sub-{subject_id}',
                    'ses-off', 'eeg', 'sub-pd14_ses-off_task-rest_eeg.bdf')
raw = mne.io.read_raw_bdf(raw_fname, preload=True)
dig_montage = mne.channels.make_standard_montage('biosemi32')
raw.drop_channels([ch for ch in raw.ch_names
                   if ch not in dig_montage.ch_names])
raw.set_montage(dig_montage)  # use the standard montage
epochs = mne.make_fixed_length_epochs(raw, duration=3, preload=True)
                                      
ar = autoreject.AutoReject(n_interpolate=[1, 2, 3, 4], random_state=11,
                           n_jobs=1, verbose=True)
ar.fit(epochs[:20])  # fit on a few epochs to save time
```

BTW, progressbar is working in IPython console...

![Screenshot 2021-10-04 at 17 10 32](https://user-images.githubusercontent.com/73893616/135876725-159ca74f-b640-4b46-8985-ddd9894974b3.png)

So similarly, it looks like a problem with Spyder's IPython console (and probably `spyder-kernels`).

**Comment by hoechenberger** [comment] 2021-10-04 15:13
Oh, interesting. So autoreject is in fact running into the same issue! Thanks for the clarification!

**Comment by mscheltienne** [comment] 2021-10-04 15:16
@hoechenberger Yes, and I think auto-reject also runs into https://github.com/spyder-ide/spyder/issues/6172, I remember seeing it pop up a couple of times in my Spyder's IPython console.

**Comment by jasmainak** [comment] 2021-10-04 20:28
Autoreject is using MNE progressbar now since #227 so it might need to be fixed upstream :)

**Comment by mscheltienne** [comment] 2021-10-05 10:58
@jasmainak Is it? I feel like it's working with MNE because MNE has the proper dependencies in the requirements, while they are missing in autoreject.

<details close>
<summary>Code snippet (similar to above but with wrong `verbose=True` removed ):</summary>
<br>

```
import os.path as op

import mne
import autoreject


directory = '/Users/scheltie/Documents/datasets/openneuro/ds002778/'
subject_id = 'pd14'
raw_fname = op.join(directory, f'sub-{subject_id}',
                    'ses-off', 'eeg', 'sub-pd14_ses-off_task-rest_eeg.bdf')
raw = mne.io.read_raw_bdf(raw_fname, preload=True)
dig_montage = mne.channels.make_standard_montage('biosemi32')
raw.drop_channels([ch for ch in raw.ch_names
                   if ch not in dig_montage.ch_names])
raw.set_montage(dig_montage)  # use the standard montage
epochs = mne.make_fixed_length_epochs(raw, duration=3, preload=True)
                                      
ar = autoreject.AutoReject(n_interpolate=[1, 2, 3, 4], random_state=11,
                           n_jobs=1)
ar.fit(epochs[:20])  # fit on a few epochs to save time
```

</details>

I have several venv setup, in one of them, both verbose `progressbar` and `tqdm` are working in both IPython console and Spyder's IPython console, while in the venv with autoreject setup with every dependencies, I ran into the problem shown above.

**Disclaimer**: In IPython console, it is working, but with the bug https://github.com/spyder-ide/spyder/issues/6172 that need a fix upstream.

<details close>
<summary>Autoreject test environment</summary>
<br>

```
Package                       Version   Location
----------------------------- --------- ----------------------------------------
aiofiles                      0.7.0
alabaster                     0.7.12
anyio                         3.3.2
appdirs                       1.4.4
appnope                       0.1.2
argon2-cffi                   21.1.0
attrs                         21.2.0
autoreject                    0.3.dev0  /Users/scheltie/Documents/git/autoreject
Babel                         2.9.1
backcall                      0.2.0
bleach                        4.1.0
build                         0.7.0
certifi                       2021.5.30
cffi                          1.14.6
charset-normalizer            2.0.6
check-manifest                0.47
click                         8.0.1
cloudpickle                   2.0.0
coverage                      6.0
cycler                        0.10.0
Cython                        0.29.24
debugpy                       1.4.3
decorator                     5.1.0
defusedxml                    0.7.1
docutils                      0.17.1
entrypoints                   0.3
flake8                        3.9.2
graphql-core                  3.1.6
h11                           0.12.0
h5py                          3.4.0
httpcore                      0.13.7
httpx                         0.19.0
idna                          3.2
imagesize                     1.2.0
iniconfig                     1.1.1
ipykernel                     6.4.1
ipython                       7.28.0
ipython-genutils              0.2.0
jedi                          0.18.0
Jinja2                        3.0.1
joblib                        1.0.1
jsonschema                    4.0.1
jupyter-client                6.1.12
jupyter-core                  4.8.1
jupyterlab-pygments           0.1.2
jupyterlab-widgets            1.0.2
kiwisolver                    1.3.2
MarkupSafe                    2.0.1
matplotlib                    3.4.3
matplotlib-inline             0.1.3
mccabe                        0.6.1
mistune                       0.8.4
mne                           0.23.4
nbclient                      0.5.4
nbconvert                     6.2.0
nbformat                      5.1.3
nest-asyncio                  1.5.1
notebook                      6.4.4
numpy                         1.21.2
numpydoc                      1.1.0
openneuro-py                  2021.9
packaging                     21.0
pandocfilters                 1.5.0
parso                         0.8.2
pep517                        0.11.0
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.3.2
pip                           21.2.4
pluggy                        1.0.0
pooch                         1.5.1
prometheus-client             0.11.0
prompt-toolkit                3.0.20
ptyprocess                    0.7.0
py                            1.10.0
pycodestyle                   2.7.0
pycparser                     2.20
pyflakes                      2.3.1
Pygments                      2.10.0
pyparsing                     2.4.7
PyQt5                         5.15.4
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.9.0
pyrsistent                    0.18.0
pytest                        6.2.5
pytest-cov                    3.0.0
pytest-sugar                  0.9.4
python-dateutil               2.8.2
pytz                          2021.3
pyzmq                         22.3.0
requests                      2.26.0
rfc3986                       1.5.0
scikit-learn                  1.0
scipy                         1.7.1
Send2Trash                    1.8.0
setuptools                    58.2.0
sgqlc                         14.1
six                           1.16.0
sniffio                       1.2.0
snowballstemmer               2.1.0
Sphinx                        4.2.0
sphinx-bootstrap-theme        0.8.0
sphinx-gallery                0.10.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder-kernels                2.1.3
termcolor                     1.1.0
terminado                     0.12.1
testpath                      0.5.0
threadpoolctl                 3.0.0
toml                          0.10.2
tomli                         1.2.1
tornado                       6.1
tqdm                          4.62.3
traitlets                     5.1.0
urllib3                       1.26.7
wcwidth                       0.2.5
webencodings                  0.5.1
wheel                         0.37.0
widgetsnbextension            3.5.1
wurlitzer                     3.0.2
```

</details>


<details close>
<summary>Environment with working progress bars</summary>
<br>

```
Package             Version
------------------- ---------
aiofiles            0.7.0
anyio               3.3.2
appdirs             1.4.4
appnope             0.1.2
apptools            5.1.0
argon2-cffi         20.1.0
async-generator     1.10
attrs               21.2.0
autoreject          0.2.2
backcall            0.2.0
bleach              4.0.0
bsl                 0.1.2
certifi             2021.5.30
cffi                1.14.6
charset-normalizer  2.0.4
click               8.0.1
cloudpickle         1.6.0
configobj           5.0.6
cycler              0.10.0
debugpy             1.4.1
decorator           5.0.9
defusedxml          0.7.1
Deprecated          1.2.12
dipy                1.4.1
entrypoints         0.3
envisage            6.0.1
graphql-core        3.1.6
h11                 0.12.0
h5py                3.3.0
httpcore            0.13.7
httpx               0.19.0
idna                3.2
imageio             2.9.0
imageio-ffmpeg      0.4.4
importlib-metadata  4.6.3
importlib-resources 5.2.2
ipycanvas           0.9.0
ipyevents           2.0.1
ipykernel           6.1.0
ipython             7.26.0
ipython-genutils    0.2.0
ipyvtklink          0.2.1
ipywidgets          7.6.3
jedi                0.18.0
Jinja2              3.0.1
joblib              1.0.1
jsonschema          3.2.0
jupyter             1.0.0
jupyter-client      6.1.12
jupyter-console     6.4.0
jupyter-core        4.7.1
jupyterlab-pygments 0.1.2
jupyterlab-widgets  1.0.0
kiwisolver          1.3.1
llvmlite            0.36.0
MarkupSafe          2.0.1
matplotlib          3.4.3
matplotlib-inline   0.1.2
mayavi              4.7.3
meshio              4.4.6
mffpy               0.6.3
mistune             0.8.4
mne                 0.23.0
nbclient            0.5.3
nbconvert           6.1.0
nbformat            5.1.3
nest-asyncio        1.5.1
nibabel             3.2.1
nilearn             0.8.0
notebook            6.4.3
numba               0.53.1
numexpr             2.7.3
numpy               1.21.2
opencv-python       4.5.3.56
openneuro-py        2021.9
packaging           21.0
pandas              1.3.1
pandocfilters       1.4.3
parso               0.8.2
patsy               0.5.1
pexpect             4.8.0
pickleshare         0.7.5
Pillow              8.3.1
pip                 21.2.4
pooch               1.5.1
prometheus-client   0.11.0
prompt-toolkit      3.0.19
psutil              5.8.0
ptyprocess          0.7.0
pycparser           2.20
pyface              7.3.0
Pygments            2.9.0
pylsl               1.15.0
pyparsing           2.4.7
pyprep              0.3.1
PyQt5               5.15.4
PyQt5-Qt5           5.15.2
PyQt5-sip           12.9.0
pyqtgraph           0.12.2
pyrsistent          0.18.0
pysurfer            0.11.0
python-dateutil     2.8.2
python-picard       0.6
pytz                2021.1
pyvista             0.31.3
pyvistaqt           0.5.0
pyzmq               22.2.1
qtconsole           5.1.1
QtPy                1.9.0
requests            2.26.0
rfc3986             1.5.0
scikit-learn        0.24.2
scipy               1.7.1
scooby              0.5.7
seaborn             0.11.2
Send2Trash          1.8.0
setuptools          58.1.0
sgqlc               14.1
sip                 6.1.1
six                 1.16.0
sniffio             1.2.0
sounddevice         0.4.2
spyder-kernels      2.1.1
statsmodels         0.12.2
terminado           0.11.0
testpath            0.5.0
threadpoolctl       2.2.0
toml                0.10.2
tornado             6.1
tqdm                4.62.0
traitlets           5.0.5
traits              6.2.0
traitsui            7.2.1
transforms3d        0.3.1
urllib3             1.26.6
vtk                 9.0.1
wcwidth             0.2.5
webencodings        0.5.1
wheel               0.37.0
widgetsnbextension  3.5.1
wrapt               1.12.1
wurlitzer           2.1.1
xlrd                2.0.1
zipp                3.5.0
```

</details>

**Comment by mscheltienne** [comment] 2021-10-05 11:19
A quick differencial: 

```
env:           autoreject      working

-----------------------
Autoreject dependencies

autoreject      0.3.dev0        0.2.2
numpy           1.21.2          1.21.2
scipy           1.7.1           1.7.1
mne             0.23.4          0.23.0
scikit-learn    1.0             0.24.2
joblib          1.0.1           1.0.1
matplotlib      3.4.3           3.4.3
tqdm            4.62.3          4.62.0
h5py            3.4.0           3.3.0
pytest          6.2.5           ----
pytest-cov      3.0.0           ----
pytest-sugar    0.9.4           ----
check-manifest  0.47            ----
flake8          3.9.2           ----
pooch           1.5.1           1.5.1
sphinx          4.2.0           ----
sphinx-gallery  0.10.0          ----
sphinx_bootstrap_theme 0.8.0    ----
numpydoc        1.1.0           ----
cython          0.29.24         ----
pillow          8.3.2           8.3.1
openneuro-py    2021.9          2021.9

----------------------------------------
Difference that might explain the second
environment working. 

ipywidgets      ----            7.6.3
ipycanvas       ----            0.9.0
ipyevents       ----            2.0.1
ipykernel       6.4.1           6.1.0
ipython         7.28.0          7.26.0
jupyter         ----            1.0.0
jupyter-client  6.1.12          6.1.12
jupyter-console ----            6.4.0
jupyter-core    4.8.1           4.7.1
jupyterlab-pygments  0.1.2      0.1.2
jupyterlab-widgets   1.0.2      1.0.0
```

**Comment by jasmainak** [comment] 2021-10-05 16:58
humm, we can remove `tqdm` from the dependencies here: https://github.com/autoreject/autoreject/blob/97d401c6af1ea870fdc56ca49345dec06833af74/setup.py#L63

would that solve your problem? We literally don't use it anywhere in the codebase and you should just use the MNE environment for autoreject

**Comment by mscheltienne** [comment] 2021-10-08 14:21
I feel like progressbar have always been an issue with Spyder's console. It's very weird that depending on which dependency is installed, it sometimes works, sometimes it shows this weird HBox display, and sometimes it raises...
I doubt this is worth any change in `autoreject` or `MNE`, even if there is a combination of dependency (too lazy to look for it) that does make it work in all 3, python console, IPython console and Spyder's console.

**Comment by jasmainak** [comment] 2021-10-14 05:44
Sorry for the delay in responding as I'm on vacation currently.

Back in the day I used to recommend installing `matplotlib` separately with conda because the `pip` install often broke things with IPython, Spyder et al. as you've rightly noticed. However, the Python ecosystem has moved towards putting the dependencies in `install_requires` of setup.py so you run one command and everything is installed. 

I have a feeling that if you mirror the minimum versions of the autoreject dependencies from `requirements.txt` in MNE-Python, this might fix the issue as nothing new will be installed if you already are using the MNE env. What do you think?

**Comment by jasmainak** [comment] 2021-10-14 09:31
I suggest starting from a fresh virtual environment in conda and sharing the steps needed to reproduce rather than sharing the environment file :) I'll give you the first command:

```sh
$ conda create -n autoreject python=3.8
```

Now do the steps you suggest above and let me know if it works or not

**Comment by hoechenberger** [comment] 2021-10-14 11:52
@jasmainak So are you saying `tqdm` is not required by `autoreject`? Then I could drop the `tqdm` dependency for the `conda-forge` package as well.

**Comment by jasmainak** [comment] 2021-10-18 12:59
let's close then.

**Closed by jasmainak** 2021-10-18 12:59 UTC

**Comment by szerfas1** [comment] 2022-03-28 21:02
This just broke for me too:
```
import autoreject
# compute channel-level rejections
ar = autoreject.AutoReject(n_interpolate=[], random_state=11, n_jobs=1, verbose=True)
# ar.fit(baseline_epochs)
epochs_ar, reject_log = ar.fit_transform(baseline_epochs, return_log=True)
baseline_epochs[reject_log.bad_epochs].plot(scalings=dict(eeg=10e-4))
```
Results in:
<details>
<summary>Traceback</summary>
<br>
```
Running autoreject on ch_type=eeg
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/var/folders/r4/qwgkc9mx07q9bpphs0bw85gm0000gn/T/ipykernel_92199/2985395865.py in <module>
      3 ar = autoreject.AutoReject(n_interpolate=[], random_state=11, n_jobs=1, verbose=True)
      4 # ar.fit(baseline_epochs)
----> 5 epochs_ar, reject_log = ar.fit_transform(baseline_epochs, return_log=True)
      6 baseline_epochs[reject_log.bad_epochs].plot(scalings=dict(eeg=10e-4))
      7 

~/src/jhana_proj/conda-env/lib/python3.9/site-packages/autoreject/autoreject.py in fit_transform(self, epochs, return_log)
   1141             The rejection log. Returned only of return_log is True.
   1142         """
-> 1143         return self.fit(epochs).transform(epochs, return_log=return_log)
   1144 
   1145     def save(self, fname, overwrite=False):

~/src/jhana_proj/conda-env/lib/python3.9/site-packages/autoreject/autoreject.py in fit(self, epochs)
   1009                 print('Running autoreject on ch_type=%s' % ch_type)
   1010             this_local_reject, this_loss = \
-> 1011                 _run_local_reject_cv(epochs, thresh_func, this_picks,
   1012                                      self.n_interpolate, self.cv_,
   1013                                      self.consensus, self.dots,

~/src/jhana_proj/conda-env/lib/python3.9/site-packages/autoreject/autoreject.py in _run_local_reject_cv(epochs, thresh_func, picks_, n_interpolate, cv, consensus, dots, verbose)
    768                                verbose=verbose, picks=picks_,
    769                                dots=dots)
--> 770     local_reject.fit(epochs)
    771 
    772     assert len(local_reject.consensus_) == 1  # works with one ch_type

~/src/jhana_proj/conda-env/lib/python3.9/site-packages/autoreject/autoreject.py in fit(self, epochs)
    682         self.consensus_[ch_type] = self.consensus
    683 
--> 684         self.threshes_ = self.thresh_func(
    685             epochs.copy(), dots=self.dots, picks=self.picks_,
    686             verbose=self.verbose)

~/src/jhana_proj/conda-env/lib/python3.9/site-packages/autoreject/autoreject.py in _compute_thresholds(epochs, method, random_state, picks, augment, dots, verbose, n_jobs)
    437         data, y = epochs.get_data(), np.ones((n_epochs, ))
    438         if augment:
--> 439             epochs_interp = _clean_by_interp(epochs, picks=picks,
    440                                              dots=dots, verbose=verbose)
    441             # non-data channels will be duplicate

~/src/jhana_proj/conda-env/lib/python3.9/site-packages/autoreject/utils.py in _clean_by_interp(inst, picks, dots, verbose)
    226     BaseEpochs = _get_epochs_type()
    227     ch_names = [inst.info['ch_names'][p] for p in picks]
--> 228     for ch_idx, (pick, ch) in enumerate(_pbar(list(zip(picks, ch_names)),
    229                                         desc=mesg, verbose=verbose)):
    230         inst.info['bads'] = [ch]

~/src/jhana_proj/conda-env/lib/python3.9/site-packages/autoreject/utils.py in _pbar(iterable, desc, verbose, **kwargs)
    177     if verbose:
    178         from mne.utils.progressbar import ProgressBar
--> 179         pbar = ProgressBar(iterable, mesg=desc, **kwargs)
    180     else:
    181         pbar = iterable

~/src/jhana_proj/conda-env/lib/python3.9/site-packages/mne/utils/progressbar.py in __init__(self, iterable, initial_value, mesg, max_total_width, max_value, **kwargs)
     78         self._mmap = None
     79         disable = logger.level > logging.INFO or which_tqdm == 'off'
---> 80         self._tqdm = tqdm(
     81             iterable=self.iterable, desc=mesg, total=self.max_value,
     82             initial=initial_value, ncols=max_total_width,

~/src/jhana_proj/conda-env/lib/python3.9/site-packages/tqdm/notebook.py in __init__(self, *args, **kwargs)
    240         unit_scale = 1 if self.unit_scale is True else self.unit_scale or 1
    241         total = self.total * unit_scale if self.total else self.total
--> 242         self.container = self.status_printer(self.fp, total, self.desc, self.ncols)
    243         self.container.pbar = proxy(self)
    244         self.displayed = False

~/src/jhana_proj/conda-env/lib/python3.9/site-packages/tqdm/notebook.py in status_printer(_, total, desc, ncols)
    113         # Prepare IPython progress bar
    114         if IProgress is None:  # #187 #451 #558 #872
--> 115             raise ImportError(
    116                 "IProgress not found. Please update jupyter and ipywidgets."
    117                 " See [https://ipywidgets.readthedocs.io/en/stable"](https://ipywidgets.readthedocs.io/en/stable%22)

ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
```
</details>

**Comment by jasmainak** [comment] 2022-03-29 05:04
what version of MNE are you using @szerfas1 ?

**Comment by szerfas1** [comment] 2022-03-30 02:46
Ah, I didn't realize I had fallen behind the latest version. I was on 0.24.1 and I see 1.0 is now out.

I just upgraded with `pip install -U mne` to 1.0 and got a different error about mne/externals, which I was struggling to find in my site-packages. Then I created an entirely new conda env, which worked fine. Thanks for asking :)

Slick new visualizations with mne-1.0!
