### ISSUE TITLE
Error during fit_transform -  RuntimeWarning: Mean of empty slice and RuntimeWarning: mean of empty slice. radius_init = radii.mean()

### ISSUE THREAD

**Issue by AmirDJV** [autoreject/autoreject#133] opened 2019-02-28 08:59 UTC
Hi, 

I encountered two (I think they are the same) errors while running 
```
ar = AutoReject(picks=picks, random_state=42, n_jobs=2, verbose='tqdm')
arEpochs, arReject_log = ar.fit_transform(epochs, return_log=True) 
```
If I run the code in spyder I get:

> RuntimeWarning: mean of empty slice. radius_init = radii.mean()

In jupyter notebook I get: 

> RuntimeWarning: Mean of empty slice

Running the script in anaconda prompt directly will also cause it to crash. 

The odd part is that if I will crop my raw/epochs (not all crops though) it will run perfect. 

Reproducible example using this [data](https://github.com/AmirDJV/github-question/blob/master/data/test_raw.fif) in a jupyter notebook can be found [here](https://github.com/AmirDJV/github-question/blob/master/Autoreject%20runtime%20error.ipynb) (the repository can be found [here](https://github.com/AmirDJV/github-question). 

Thank you!

**Comment by jasmainak** [comment] 2019-02-28 23:38
I confirm the problem. Thanks for reporting. If we put

```py
import warnings
warnings.filterwarnings('error')
```

at the top of your script, you can find that somehow autoreject is trying to interpolate all the channels for a particular epoch. It's because the default `n_interpolate` is `np.array([1, 4, 32])` and you have 32 channels. The easy fix for you is to change this to something like `np.array([1, 2, 4, 8])`.

However, I need to investigate further why it's hitting this particular corner case.

**Comment by AmirDJV** [comment] 2019-03-01 11:52
Thank you for the prompt response and solution. 

However, I didn't fully understand what `n_interpolate` does? 

In addition, If there's anything I can do to help please tell me :)

**Comment by jasmainak** [comment] 2019-03-01 18:57
The `n_interpolate` is the `rho` in the Autoreject paper. It's the maximum number of electrodes that autoreject can interpolate in an epoch. Because if you try to interpolate too many electrodes, it will not improve signal quality. But since this is not known beforehand, you learn it by searching over many potential values. That's why `n_interpolate` is an array.

**Comment by jasmainak** [comment] 2019-10-25 22:01
closing this issue as nobody has hit it again and the code to reproduce is no longer available.

**Closed by jasmainak** 2019-10-25 22:01 UTC
Labels: bug
